go_import_path: github.com/spf13/viper

language: go

env:
  global:
  - GO111MODULE="on"

go:
  - 1.11.x
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go install ./...

  # Ensure no dependencies were added without encoding them in go.mod/go.sum.
  - go mod tidy
  - git diff go.mod | tee /dev/stderr | (! read)
  - git diff go.sum | tee /dev/stderr | (! read)

  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v ./...

after_success:
  - go get -u -d github.com/spf13/hugo
  - cd $GOPATH/src/github.com/spf13/hugo && make && ./hugo -s docs && cd -

sudo: false
